### ISSUE TITLE
Modelo de *card*

### ISSUE THREAD

**Issue by adson360** [rogerioplima/PJI110-0010-FRANCO-DA-ROCHA-Grupo-001#1]
🆕 **Update:** a ideia do uso de cards não vingou durante a reunião de 02NOV21 (#2) , por isso essa *issue* está sendo fechada e recebendo a etiqueta branca _wontfix_.

---

🎯 **Alvo:** Esclarecer atividades de forma clara e concisa para o responsável pelas ações e para toda a equipe;

### **Atividade**
🧑‍ @responsável @substituto.presente

🧾 Descrição
🔍 Detalhes

- [x] Aqui as tarefas devem ser quebradas em pedaços menores
- [x] O tempo de cada tarefa é planejado para ser feita em até um dia
- [x] Cada linha desta lista é pensada de forma que não exija mais que 4h de trabalho
- [x] A execução dessa lista é de responsabilidade do dono do card
- [x] Todos devem ajudar na criação dessa lista hoje, destrinchando a solução dos problemas

:reminder_ribbon: Lembrete
:hammer_and_wrench: Ferramentas
:date: Prazo

### Desenho de páginas
🧑‍ @luzmichele
🧾 Desenhar todas as telas que o usuário e os admins possam navegar.

- [ ] Montar um fluxograma para navegação entre as telas, desenhando um fluxo das ações.
[exemplo1](https://www.freecodecamp.org/news/content/images/2020/09/Wireframe.svg); [exemplo2](https://previews.123rf.com/images/lisenok94144/lisenok941441607/lisenok94144160700002/59778241-set-of-simple-flat-website-templates-web-wireframe-vector-ux-interface-page-design-prototype-example.jpg)
- [ ] Mapa do site [exemplo](https://natomadaproducoes.com.br/wp-content/uploads/2021/04/sitemap-XML.jpg)
- [ ] Desenhar cada página que o Usuário vai/pode utilizar. 

:reminder_ribbon: **Lembretes:**

- as páginas para smartphone também deverão ser desenhadas.
- auxiliar nas questões de estilo e design para implementação do HTML e CSS
- conversar com o banco de dados para incluir/remover/alterar campos necessários
- deixar clara as ações dos botões e o **destino** quando clicado

:hammer_and_wrench: **Ferramentas sugeridas:**

[Draw](draw.io), MS Office Publisher, Libre Office Draw (ou papeis e canetinhas 📐 📋🖍️ 🖊️ )

:date: **Prazo:** Domingo **08NOV21**

# Cards

- [ ] Desenho de páginas
- [ ] Escrever arquivos HTML e CSS
- [ ] Escrever instruções SQL

📚 **Referências:**
[GitHub. **Mastering Issues**](https://guides.github.com/features/issues/)

**Comment by rogerioplima** [comment]
Não tenho certeza mas acho que não precisa desenhar a tela para celular
