### ISSUE TITLE
Reunião TER 02NOV21

### ISSUE THREAD

**Issue by adson360** [rogerioplima/PJI110-0010-FRANCO-DA-ROCHA-Grupo-001#2]
# Ata de reunião
📜 **Pauta:** Definição de detalhes responsabilidades para execução do projeto
📅 **Data:** Terça feira, 02 de novembro 2021 às 19:00
📌 **Local:** Collaborate (AVA Univesp - BlackBoard)

✋ **Convidados:**

- [ausente] Danilo
- [ausente] Michele
- [ausente] Rene
- [presente] João
- [presente] Valdomiro
- [presente] Rogério
- [presente] Adson

🎯 **Objetivos:**

-  ~~Definir o *Product Owner*~~
- [x] Definir os requisitos do projeto
- [x] Elaborar lista de atividades
- [x] Delegar cada atividade a um integrante

📝 **Acompanhamentos e definições:**

- [x] As atividades serão definidas em blocos, conforme modelo   #1 
- [x] O resultados das atividades serão postadas para todo o grupo em #
- [x] Esclarecer para todos do grupo as camadas web
- [x] ~~Trello? Notion? Mural na parede?~~
- [x] Workflow claro e suscinto da navegação dos usuários (veja "Encaminhamentos)
- [x] Workflow claro e suscinto da navegação do administrador/coletor/diretor/professores (veja "Encaminhamentos)
- [x] ~~Criação dos blocos de atividades detalhados,~~
- [x] Momento de identificação de falhas lógicas (veja "Encaminhamentos)

✅ **Encaminhamentos:**

Valdomiro - 
Adson - 
João - 

Ao final da reunião, o @joaomininel divulgou para o restante da equipe no grupo de Whatsapp:
>Pessoal, boa noite. Conforme a nossa reunião de hoje, definimos alguns pontos importantes para seguirmos com nosso projeto.
>Estabelecemos o fluxo dos processos envolvidos, tanto do usuário/doador quanto do coletor.
>Postarei o diagrama aqui no grupo até o fim do dia de amanhã.
>Definimos também algumas atribuições sobre as próximas entregas.
>O Valdomiro focará no back end, com apoio dos demais integrantes e o Adson focará no desenvolvimento do banco de dados.
>Após o fluxo de processos, o banco de dados e o back end, precisaremos focar no front end, que deve mudar consideravelmente do que foi proposta inicialmente.
>O Adson sugeriu o uso da ferramenta WireFrame, para os desenhos das telas nessa etapa.
>Os nossos prazos estão apertados, a próxima reunião com a orientadora será em 11 de novembro, por isso é importante que a gente una esforços e que publiquemos tudo o que for sendo desenvolvido (principalmente no GitHub).
>Tmj, pessoal. Abraço e boa noite a todos.

📚 **Referências:**
[NASCIMENTO, Thiago. **Ata de Reunião: Como fazer de forma efetiva e ágil**](https://thiagonasc.com/produtividade/ata-de-reuniao-como-fazer-atualizado)
[GitHub. **Mastering Markdown**](https://guides.github.com/features/mastering-markdown/)

**Comment by rogerioplima** [comment]
Legal, confirmado minha presença.

**Comment by adson360** [comment]
@rogerioplima Utilizaremos o repositório aqui para centralizar o que for sendo produzido pela equipe? Em caso positivo, ficam as observações:
- Falta adicionar Valdomiro (ValdomiroCarvalho) e Danilo (não sei o perfil dele aqui no GitHub) à lista de colaboradores;
- Sugiro que utilizemos esse espaço do *issues*. Aqui tem [recursos](https://github.com/features/issues/) que podem enriquecer nossa interação se usados de forma adequada. Aqui um [guia](https://guides.github.com/features/issues/) de uso.

**Comment by rogerioplima** [comment]
Reunião efetivada.

**Comment by rogerioplima** [comment]
Vamos reagendar próxima reunião.
